name: Maven Package

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Check for new commits
      - name: Check for new commits
        run: |
          if [ -f subtraction/commit-hash.txt ]; then
            PREVIOUS_COMMIT=$(cat subtraction/commit-hash.txt)
            CURRENT_COMMIT=${{ github.sha }}
            echo "Last Commit: $PREVIOUS_COMMIT"
            echo "Current Commit: $CURRENT_COMMIT"
            if [ "$PREVIOUS_COMMIT" = "$CURRENT_COMMIT" ]; then
              echo "No new commits detected. Skipping build."
              exit 0
            else
              echo "New commits detected. Proceeding with build."
            fi
          else
            echo "No previous commit hash found. Proceeding with build."
          fi

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Clean the project
      - name: Maven Clean
        run: mvn clean
        working-directory: subtraction

      # Compile the project
      - name: Maven Compile
        run: mvn compile
        working-directory: subtraction

      # Run tests
      - name: Maven Test
        run: mvn test
        working-directory: subtraction

      # Package the project
      - name: Maven Package
        run: mvn package
        working-directory: subtraction

      # Store commit hash in a file
      - name: Save Commit Hash
        run: echo "${{ github.sha }}" > subtraction/commit-hash.txt

      # Upload commit hash as an artifact
      - name: Upload Commit Hash
        uses: actions/upload-artifact@v3
        with:
          name: commit-hash
          path: subtraction/commit-hash.txt