name: Maven Package

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'subtraction/commit-hash.txt' # Ignore pushes that only modify this file

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_PAT }}
          fetch-depth: 0

      # Check for new commits
      - name: Check for new commits
        run: |
          if [ -f subtraction/commit-hash.txt ]; then
            PREVIOUS_COMMIT=$(cat subtraction/commit-hash.txt)
            CURRENT_COMMIT=${{ github.sha }}
            echo "Last Commit: $PREVIOUS_COMMIT"
            echo "Current Commit: $CURRENT_COMMIT"
            if [ "$PREVIOUS_COMMIT" = "$CURRENT_COMMIT" ]; then
              echo "No new commits detected. Skipping build."
              exit 0
            else
              echo "New commits detected. Proceeding with build."
            fi
          else
            echo "No previous commit hash found. Proceeding with build."
          fi

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Clean the project
      - name: Maven Clean
        run: mvn clean
        working-directory: subtraction

      # Compile the project
      - name: Maven Compile
        run: mvn compile
        working-directory: subtraction

      # Run tests
      - name: Maven Test
        run: mvn test
        working-directory: subtraction

      # Package the project
      - name: Maven Package
        run: mvn package
        working-directory: subtraction

      # Store commit hash in a file
      - name: Save Commit Hash
        run: echo "${{ github.sha }}" > subtraction/commit-hash.txt

      # Create a new branch for the commit
      - name: Create Branch
        run: |
          git checkout -b update-commit-hash
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add subtraction/commit-hash.txt
          git commit -m "Update commit-hash.txt with latest commit hash"
          git push origin update-commit-hash

      # Create a pull request using the GitHub REST API
      - name: Create Pull Request
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.WORKFLOW_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{
              "title": "Update commit-hash.txt",
              "body": "This pull request updates the commit-hash.txt file with the latest commit hash.",
              "head": "update-commit-hash",
              "base": "main"
            }'