name: Maven Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/subtraction/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Clean the project
      - name: Maven Clean
        run: mvn clean
        working-directory: subtraction

      # Compile the project
      - name: Maven Compile
        run: mvn compile
        working-directory: subtraction

      # Run tests
      - name: Maven Test
        run: mvn test
        working-directory: subtraction

      # Package the project
      - name: Maven Package
        run: mvn package
        working-directory: subtraction